# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: Orderer
    Domain: trace.com
    # ---------------------------------------------------------------------------
    # "Specs" - See PeerOrgs below for complete description
    # ---------------------------------------------------------------------------
    Specs:
      - Hostname: orderer
# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  # Org1 母线使用甲方
  # ---------------------------------------------------------------------------
  - Name:
      OrgFirstParty         #使用者
    Domain: orgfirstparty.trace.com
    EnableNodeOUs: true  #支持nodejs
    Template:            #节点数             
        Count: 2
    Users:               #组织中用户数目
      Count: 1
  # ---------------------------------------------------------------------------
  # Org2  质量监管单位，包括政府监管部门/生产过程中的监管者/安装过程中的监理单位
  # ---------------------------------------------------------------------------
  - Name:
      OrgSuperv       #质量监管者
    Domain: orgsuperv.trace.com
    EnableNodeOUs: true  #支持nodejs
    Template:            #节点数             
      Count: 2           #存储数据的节点
    Users:               #组织中用户数目
      Count: 3           #生产中质量监管者/安装中质量监管者/上层质量监管者
  # ---------------------------------------------------------------------------
  # Org3  现场安装施工单位
  # ---------------------------------------------------------------------------
  - Name:
      OrgInstall      #现场安装者
    Domain: orginstall.trace.com
    EnableNodeOUs: true
    Template:            #节点数             
      Count: 2           #存储数据的节点
      Users:               #组织中用户数目
        Count: 1          #现场安装者
  # ---------------------------------------------------------------------------
  # Org4  母线生产工厂，如施耐德
  # ---------------------------------------------------------------------------
  - Name:
      OrgProduce     #母线生产者
    Domain: orgproduce.trace.com
    EnableNodeOUs: true
    Template:            #节点数             
      Count: 2           #存储数据的节点
      Users:               #组织中用户数目
          Count: 1
  # ---------------------------------------------------------------------------
  # Org5  零件生产工厂，如铜排/外科/绝缘材料
  # ---------------------------------------------------------------------------
  - Name:
      OrgPartProduce      #零件生产者
    Domain: orgpartproduce.trace.com
    EnableNodeOUs: true
    Template:            #节点数             
      Count: 2           #存储数据的节点
      Users:               #组织中用户数目
        Count: 3          #母线的零件提供者
  # ---------------------------------------------------------------------------
  # Org6  零件及母线运输公司
  # ---------------------------------------------------------------------------
  - Name:
      OrgTransit      #运输者
    Domain: orgtransit.trace.com
    EnableNodeOUs: true
    Template:            #节点数             
      Count: 2           #存储数据的节点
      Users:               #组织中用户数目
        Count: 3          #运输公司

