version: '2'

services:

  peer0.orgproduce.trace.com:
    container_name: peer0.orgproduce.trace.com
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=trace_default
      - CORE_LOGGING_LEVEL=INFO
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_GOSSIP_USELEADERELECTION=true  #leader节点自动选择
      - CORE_PEER_GOSSIP_ORGLEADER=false         #当前节点是否为主节点
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_LOCALMSPID=OrgProduceMSP
      - CORE_PEER_ID=peer0.orgproduce.trace.com
      - CORE_PEER_ADDRESS=peer0.orgproduce.trace.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.orgproduce.trace.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.orgproduce.trace.com:7051
      # TLS
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/orgproduce.trace.com/peers/peer0.orgproduce.trace.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/orgproduce.trace.com/peers/peer0.orgproduce.trace.com/tls:/etc/hyperledger/fabric/tls
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    networks:
      default:
        aliases:
          - trace
    ports:
      - 7351:7051
      - 7353:7053

  cli3:
    container_name: cli3
    image: hyperledger/fabric-tools:latest
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ID=cli3
      - CORE_PEER_ADDRESS=peer0.orgproduce.trace.com:7051
      - CORE_PEER_LOCALMSPID=OrgProduceMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orgproduce.trace.com/peers/peer0.orgproduce.trace.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orgproduce.trace.com/peers/peer0.orgproduce.trace.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orgproduce.trace.com/peers/peer0.orgproduce.trace.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orgproduce.trace.com/users/Admin@orgproduce.trace.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ./chaincode/:/opt/gopath/src/github.com/chaincode
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      #- ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
      - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - peer0.orgproduce.trace.com

    networks:
      default:
        aliases:
          - trace

