# 配置文件的名字,可以不写
name: "ts-service-network"

version: 1.0.0

# client 相关配置
client:
  # 此 SDK 实例属于哪个组织
  organization: OrgInstall
  # 日志级别
  logging:
    level: info
  # 证书所在目录
  cryptoconfig:
    path: /home/ts/workspace/src/origins/conf/crypto-config
  # 这种方式就是把用户名和密码直接存储在本地的一个文件中，而用户和密码对通过一个别名来引用，这样可以避免密码明文格式可能会存在的安全问题
  credentialStore:
    path: /tmp/ts-service-store

  # 区块链密码服务提供者,指定加密策略
  BCCSP:
    security:
      enabled: true
      default:
        provider: "SW"
      hashAlgorithm: "SHA2"
      softVerify: true
      level: 256

  tlsCerts:
    # 证书池策略，默认为false,提高身份认证速率
    systemCertPool: true
    client:
      keyfile: /home/ts/workspace/src/origins/conf/crypto-config/peerOrganizations/orginstall.trace.com/users/User1@ofgj.itcast.cn/tls/client.key
      certfile: /home/ts/workspace/src/origins/conf/crypto-config/peerOrganizations/orginstall.trace.com/users/User1@ofgj.itcast.cn/tls/client.crt


# channel 相关配置
channels:
  # channelID
  TransitOrgschannel:
    # orderer 组织必须指定
    orderers:
      - orderer.trace.com
    # 添加到该 channel 中的组织的 peer 列表
    peers:
      peer0.orginstall.trace.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      peer1.orginstall.trace.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true


    policies:
      queryChannelConfig:
        minResponses: 1
        maxTargets: 1
        retryOpts:
          attempts: 5
          initialBackoff: 500ms
          maxBackoff: 5s
          backoffFactor: 2.0

# organizations 相关配置
organizations:
  OrgInstall:
    # configtx.yaml organizations -> ID
    mspid: orginstall.trace.com

    cryptoPath: /home/ts/workspace/src/origins/conf/crypto-config/peerOrganizations/orginstall.trace.com/users/{userName}@orginstall.trace.com/msp
    peers:
      - peer0.orginstall.trace.com
      - peer1.orginstall.trace.com


  ordererorg:
    mspID: trace.com
    cryptoPath: /home/ts/workspace/src/origins/conf/crypto-config/ordererOrganizations/trace.com/users/Admin@trace.com/msp

# orderer 相关配置
orderers:
  orderer.trace.com:
    url: localhost:7050
    grpcOptions:
      ssl-target-name-override: orderer.trace.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: false

    tlsCACerts:
      path: /home/ts/workspace/src/origins/conf/crypto-config/ordererOrganizations/trace.com/tlsca/tlsca.trace.com-cert.pem

# peer 相关配置
peers:
  peer0.orginstall.trace.com:
    url: grpc://localhost:7051
    eventUrl: localhost:7053
    grpcOptions:
      ssl-target-name-override: peer0.orginstall.trace.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: false

    tlsCACerts:
      path: /home/ts/workspace/src/origins/conf/crypto-config/peerOrganizations/orginstall.trace.com/tlsca/tlsca.orginstall.trace.com-cert.pem

  peer1.orginstall.trace.com:
    url: localhost:8051
    eventUrl: localhost:8053
    grpcOptions:
      ssl-target-name-override: peer1.orginstall.trace.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: false

    tlsCACerts:
      path: /home/ts/workspace/src/origins/conf/crypto-config/peerOrganizations/orginstall.trace.com/tlsca/tlsca.orginstall.trace.com.pem