version: '2'

networks:
  TS_test:

services:
  orderer.trace.com:
    container_name: orderer.trace.com
    image: hyperledger/fabric-orderer:latest
    environment:
      - ORDERER_GENERAL_LOGLEVEL=INFO #info级别
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0 #监听地址
      - ORDERER_GENERAL_LISTENPORT=7050 #监听端口
      - ORDERER_GENERAL_GENESISMETHOD=file #创世块来源于文件
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS 使用TLS加密，下方为相关的证书密钥地址
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key #私钥
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt #证书
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt] #根证书
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/trace.com/orderers/orderer.trace.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/trace.com/orderers/orderer.trace.com/tls/:/var/hyperledger/orderer/tls
      #- orderer.trace.com:/var/hyperledger/production/orderer
    networks:
      default:
        aliases:
          - orderer.trace.com
    ports:
      - 7050:7050


  peer0.orgfirstparty.trace.com:
    container_name: peer0.orgfirstparty.trace.com
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=trace_default
      - CORE_LOGGING_LEVEL=INFO
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_GOSSIP_USELEADERELECTION=true  #leader节点自动选择
      - CORE_PEER_GOSSIP_ORGLEADER=false         #当前节点是否为主节点
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_LOCALMSPID=OrgFirstPartyMSP
      - CORE_PEER_ID=peer0.orgfirstparty.trace.com
      - CORE_PEER_ADDRESS=peer0.orgfirstparty.trace.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.orgfirstparty.trace.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.orgfirstparty.trace.com:7051
      # TLS
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/orgfirstparty.trace.com/peers/peer0.orgfirstparty.trace.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/orgfirstparty.trace.com/peers/peer0.orgfirstparty.trace.com/tls:/etc/hyperledger/fabric/tls
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    networks:
      default:
        aliases:
          - trace
    ports:
      - 7051:7051
      - 7053:7053

  peer1.orgfirstparty.trace.com:
    container_name: peer1.orgfirstparty.trace.com
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=trace_default
      - CORE_LOGGING_LEVEL=INFO
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_LOCALMSPID=OrgFirstPartyMSP
      - CORE_PEER_ID=peer1.orgfirstparty.trace.com
      - CORE_PEER_ADDRESS=peer1.orgfirstparty.trace.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.orgfirstparty.trace.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.orgfirstparty.trace.com:7051
      # TLS
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/orgfirstparty.trace.com/peers/peer1.orgfirstparty.trace.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/orgfirstparty.trace.com/peers/peer1.orgfirstparty.trace.com/tls:/etc/hyperledger/fabric/tls
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    networks:
      default:
        aliases:
          - trace
    ports:
      - 8051:7051
      - 8053:7053

  peer0.orginstall.trace.com:
    container_name: peer0.orginstall.trace.com
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=trace_default
      - CORE_LOGGING_LEVEL=INFO
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_GOSSIP_USELEADERELECTION=true  #leader节点自动选择
      - CORE_PEER_GOSSIP_ORGLEADER=false         #当前节点是否为主节点
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_LOCALMSPID=OrgInstallMSP
      - CORE_PEER_ID=peer0.orginstall.trace.com
      - CORE_PEER_ADDRESS=peer0.orginstall.trace.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.orginstall.trace.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.orginstall.trace.com:7051
      # TLS
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/orginstall.trace.com/peers/peer0.orginstall.trace.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/orginstall.trace.com/peers/peer0.orginstall.trace.com/tls:/etc/hyperledger/fabric/tls
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    networks:
      default:
        aliases:
          - trace
    ports:
      - 7151:7051
      - 7153:7053

  peer1.orginstall.trace.com:
    container_name: peer1.orginstall.trace.com
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=trace_default
      - CORE_LOGGING_LEVEL=INFO
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_LOCALMSPID=OrgInstallMSP
      - CORE_PEER_ID=peer1.orginstall.trace.com
      - CORE_PEER_ADDRESS=peer1.orginstall.trace.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.orginstall.trace.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.orginstall.trace.com:7051
      # TLS
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/orginstall.trace.com/peers/peer1.orginstall.trace.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/orginstall.trace.com/peers/peer1.orginstall.trace.com/tls:/etc/hyperledger/fabric/tls
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    networks:
      default:
        aliases:
          - trace
    ports:
      - 8151:7051
      - 8153:7053

  peer0.orgpartproduce.trace.com:
    container_name: peer0.orgpartproduce.trace.com
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=trace_default
      - CORE_LOGGING_LEVEL=INFO
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_GOSSIP_USELEADERELECTION=true  #leader节点自动选择
      - CORE_PEER_GOSSIP_ORGLEADER=false         #当前节点是否为主节点
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_LOCALMSPID=OrgPartProduceMSP
      - CORE_PEER_ID=peer0.orgpartproduce.trace.com
      - CORE_PEER_ADDRESS=peer0.orgpartproduce.trace.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.orgpartproduce.trace.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.orgpartproduce.trace.com:7051
      # TLS
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/orgpartproduce.trace.com/peers/peer0.orgpartproduce.trace.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/orgpartproduce.trace.com/peers/peer0.orgpartproduce.trace.com/tls:/etc/hyperledger/fabric/tls
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    networks:
      default:
        aliases:
          - trace
    ports:
      - 7251:7051
      - 7253:7053

  peer1.orgpartproduce.trace.com:
    container_name: peer1.orgpartproduce.trace.com
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=trace_default
      - CORE_LOGGING_LEVEL=INFO
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_LOCALMSPID=OrgPartProduceMSP
      - CORE_PEER_ID=peer1.orgpartproduce.trace.com
      - CORE_PEER_ADDRESS=peer1.orgpartproduce.trace.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.orgpartproduce.trace.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.orgpartproduce.trace.com:7051
      # TLS
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/orgpartproduce.trace.com/peers/peer1.orgpartproduce.trace.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/orgpartproduce.trace.com/peers/peer1.orgpartproduce.trace.com/tls:/etc/hyperledger/fabric/tls
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    networks:
      default:
        aliases:
          - trace
    ports:
      - 8251:7051
      - 8253:7053

  peer0.orgproduce.trace.com:
    container_name: peer0.orgproduce.trace.com
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=trace_default
      - CORE_LOGGING_LEVEL=INFO
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_GOSSIP_USELEADERELECTION=true  #leader节点自动选择
      - CORE_PEER_GOSSIP_ORGLEADER=false         #当前节点是否为主节点
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_LOCALMSPID=OrgProduceMSP
      - CORE_PEER_ID=peer0.orgproduce.trace.com
      - CORE_PEER_ADDRESS=peer0.orgproduce.trace.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.orgproduce.trace.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.orgproduce.trace.com:7051
      # TLS
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/orgproduce.trace.com/peers/peer0.orgproduce.trace.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/orgproduce.trace.com/peers/peer0.orgproduce.trace.com/tls:/etc/hyperledger/fabric/tls
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    networks:
      default:
        aliases:
          - trace
    ports:
      - 7351:7051
      - 7353:7053

  peer1.orgproduce.trace.com:
    container_name: peer1.orgproduce.trace.com
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=trace_default
      - CORE_LOGGING_LEVEL=INFO
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_LOCALMSPID=OrgProduceMSP
      - CORE_PEER_ID=peer1.orgproduce.trace.com
      - CORE_PEER_ADDRESS=peer1.orgproduce.trace.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.orgproduce.trace.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.orgproduce.trace.com:7051
      # TLS
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/orgproduce.trace.com/peers/peer1.orgproduce.trace.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/orgproduce.trace.com/peers/peer1.orgproduce.trace.com/tls:/etc/hyperledger/fabric/tls
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    networks:
      default:
        aliases:
          - trace
    ports:
      - 8351:7051
      - 8353:7053

  peer0.orgsuperv.trace.com:
    container_name: peer0.orgsuperv.trace.com
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=trace_default
      - CORE_LOGGING_LEVEL=INFO
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_GOSSIP_USELEADERELECTION=true  #leader节点自动选择
      - CORE_PEER_GOSSIP_ORGLEADER=false         #当前节点是否为主节点
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_LOCALMSPID=OrgSupervMSP
      - CORE_PEER_ID=peer0.orgsuperv.trace.com
      - CORE_PEER_ADDRESS=peer0.orgsuperv.trace.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.orgsuperv.trace.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.orgsuperv.trace.com:7051
      # TLS
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/orgsuperv.trace.com/peers/peer0.orgsuperv.trace.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/orgsuperv.trace.com/peers/peer0.orgsuperv.trace.com/tls:/etc/hyperledger/fabric/tls
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    networks:
      default:
        aliases:
          - trace
    ports:
      - 7451:7051
      - 7453:7053

  peer1.orgsuperv.trace.com:
    container_name: peer1.orgsuperv.trace.com
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=trace_default
      - CORE_LOGGING_LEVEL=INFO
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_LOCALMSPID=OrgSupervMSP
      - CORE_PEER_ID=peer1.orgsuperv.trace.com
      - CORE_PEER_ADDRESS=peer1.orgsuperv.trace.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.orgsuperv.trace.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.orgsuperv.trace.com:7051
      # TLS
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/orgsuperv.trace.com/peers/peer1.orgsuperv.trace.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/orgsuperv.trace.com/peers/peer1.orgsuperv.trace.com/tls:/etc/hyperledger/fabric/tls
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    networks:
      default:
        aliases:
          - trace
    ports:
      - 8451:7051
      - 8453:7053

  peer0.orgtransit.trace.com:
    container_name: peer0.orgtransit.trace.com
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=trace_default
      - CORE_LOGGING_LEVEL=INFO
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_GOSSIP_USELEADERELECTION=true  #leader节点自动选择
      - CORE_PEER_GOSSIP_ORGLEADER=false         #当前节点是否为主节点
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_LOCALMSPID=OrgTransitMSP
      - CORE_PEER_ID=peer0.orgtransit.trace.com
      - CORE_PEER_ADDRESS=peer0.orgtransit.trace.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.orgtransit.trace.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.orgtransit.trace.com:7051
      # TLS
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/orgtransit.trace.com/peers/peer0.orgtransit.trace.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/orgtransit.trace.com/peers/peer0.orgtransit.trace.com/tls:/etc/hyperledger/fabric/tls
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    networks:
      default:
        aliases:
          - trace
    ports:
      - 7551:7051
      - 7553:7053

  peer1.orgtransit.trace.com:
    container_name: peer1.orgtransit.trace.com
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=trace_default
      - CORE_LOGGING_LEVEL=INFO
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_LOCALMSPID=OrgTransitMSP
      - CORE_PEER_ID=peer1.orgtransit.trace.com
      - CORE_PEER_ADDRESS=peer1.orgtransit.trace.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.orgtransit.trace.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.orgtransit.trace.com:7051
      # TLS
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/orgtransit.trace.com/peers/peer1.orgtransit.trace.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/orgtransit.trace.com/peers/peer1.orgtransit.trace.com/tls:/etc/hyperledger/fabric/tls
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    networks:
      default:
        aliases:
          - trace
    ports:
      - 8551:7051
      - 8553:7053

